### ISSUE TITLE
Remove pragma compiler warnings

### ISSUE THREAD

**Issue by andrie** [jwijffels/RMETAR#4]
The compiler throws many warnings for defunct pragmas.  These warnings obscure the more meaningful compilation errors, e.g. the errors that prevent installation on OSX (#1).

I'm creating a branch to experiment with removing these pragma statements.

**Comment by jwijffels** [comment]
@andrie 
Many thanks for updating with the new mdsplib. FYI. I've incorporated all your changes and moved to using tinytest instead of testthat.
Also added functions to retrieve all current METAR data in the world and a data.frame with all airports in the world.
Feel free to push into this repository directly.

**Comment by andrie** [comment]
I think we can close this, since it was addressed in 5d72f47698edfe3d0cc06f56ceddeaa4127ae245
